### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by iubito** [albzan/eclipse-nvda#1]
Hi!
I'm new to NVDA and I don't understand how to install this add-on.
Can you explain it in readme file ?
Thanks in advance,
Sylvain

**Comment by albzan** [comment]
Hello,
You can simply go to the Releases section on the github repo and download
the .nvda-addon package.
Cheers
Alberto

2018-02-06 11:46 GMT+01:00 iubito <notifications@github.com>:

**Comment by iubito** [comment]
Hi!
Thanks for your answer but where should I put the files? in which folder?
Regards,
Sylvain


--
Sylvain Machefert

*Tous aux Balkans ! *http://www.tousauxbalkans.net

*Malatz'Banda - musique des Balkans *http://malatzbanda.bandcamp.com
*Inna Backyard - reggae cuivré *http://www.reverbnation.com/innabackyard
*Gens Bon Beur - musique épicée* Facebook / Gens Bon Beur
<https://www.facebook.com/Gens-bon-beur-183933138457040/>

*thesuntrip.com <http://thesuntrip.com/> - l'aventure en vélo solaire*
http://www.facebook.com/SylvainMachefertAventurier

*Les Compains du Velay - reconstitution historique Renaissance*
http://www.compains.org


2018-02-14 12:04 GMT+01:00 albzan <notifications@github.com>:

**Comment by albzan** [comment]
You should install it using the NVDA Add-ons manager. It is only a single
file .nvda-addon
Cheers,
Alberto

2018-02-14 16:29 GMT+01:00 iubito <notifications@github.com>:

**Comment by iubito** [comment]
OK thanks! Installed. I'll test it later
