### ISSUE TITLE
Working for eclipse version Ocygen?

### ISSUE THREAD

**Issue by kaiyasa** [albzan/eclipse-nvda#3]
I'm using oxygen release of eclipse J2EE bundle on Windows 7 with nvda 2018.x.

Since there is no install instructions, I winged it and downloaded the 0.2 zip from releases and unpack it into the dropins directory of my eclipse installation and restarted.

Trying to do a quick test, I placed a breakpoint using Control+Shift+B and only got a small chime sound and expected some kind of announcement of location.  I then did a step next with F6 and complete silence..  Am I mistaken but I expected it to read the source line it moved to.

So unless my expectation are completely unreasonable.. I fear it isn't running or installed properly.

Can I get a little help?

**Comment by albzan** [comment]
Hi,
This is an nvda addon and not an eclipse one.
To install it, you should go to Releases and download the eclipseEnhance-0.2.nvda-addon.
After that please follow the "Eclipse Configuration" heading in the readme (main page).
Cheers,
Alberto

**Comment by kaiyasa** [comment]
Well just makes me feel silly.  I had it locked in my head this was an eclipse plugin.  Works alot better installed in the right app.  I have found things are picky about when they work but don't understand the situation enough to reliably reproduce oddities.

**Comment by kaiyasa** [comment]
Done
