### ISSUE TITLE
Building code issue

### ISSUE THREAD

**Issue by alderweesh-m** [albzan/eclipse-nvda#5]
Hello,

Thanks for the good work. I tried building the addon, but I am getting an error on line 55 of the sconstruct file saying environment  name is unknown. There is no information on what build tools should be used to build the addon in the readme file, but I used the recommended tools outlined in the NVDA addons development guide to build the addon with no success.

Thank you.

**Comment by albzan** [comment]
Hello,
I updated with new scons script and I've also made some improvement.
Please, can you try to pull and rebuild?
Remember you've to have gettext and Markdown library installed before trying to build.
Cheers,
Alberto
