### ISSUE TITLE
some accessibility conflicts.

### ISSUE THREAD

**Issue by aefren** [albzan/eclipse-nvda#6]
There is a conflict in preferences/anotations options. 
if Underlined is changed to Highlighted then NVDA will stop reporting underlined each time an error is detected reviewing lines using up and down cursor and report font attributes is turned on. I think this is a great disadvantages. if underlined is selected errors can be detected in real time instead of using CTRL+. and CTRL+, keys.

**Comment by albzan** [comment]
Hi,

Yeah, You're right.

This has to do with how you're used to work when you program.

My typical use case is as follow:
* I write my code.
* I press ctrl+s to save and i got back a different sound if there are warnings or errors
* If I listen the error sound I hit ctrl+. to until I come to the error.
* If I listen the warning sound, it depends: if I'm testing I don't care, if I have to release I try to dig to fix them.

In addition with underline marks you don't have any perceeving if you are in an error or warning while you scroll using arrow keys.
How do you typically work? How do you distinguish between errors and warnings?

Cheers,

Alberto
