### ISSUE TITLE
No support for newer versions of NVDA

### ISSUE THREAD

**Issue by kaiyasa** [albzan/eclipse-nvda#7]
NVDA had an API change and upgrade to python 3 for its runtime.  So, the addOn file referenced in the README is blocked as incompatible when installing.

Any chance of getting this working?  I amusing 2020.3 and track the versions usually.

I've  been waiting for many months in hopes of a rev to support the newer NVDAs and I miss my debugger.

**Comment by albzan** [comment]
Hi,
Support is with version 0.6. I didn't updated README before.
Please try now, and let me know.
Alberto
