### ISSUE TITLE
NVDA gets an error when opening the content assist pop up in Eclipse then pressing F2

### ISSUE THREAD

**Issue by shadyar** [albzan/eclipse-nvda#9]
I attached my NVDA log file if it helps.

### Steps to reproduce:
      1. In Eclipse code editor window eg. for Java type @trans
      2. Auto completion popup will open then press F2 and choose @transient
      3. If nothing happened do step 1, 2 again.
### Actual behavior:
      NVDA plays a ding and prints some errors in NVDA log. After that NVDA no longer speak while a text is being selected.
### Expected behavior:
      NVDA should reads what is being selected via holding down Shift and pressing multiple times arrow keys.
#### NVDA installed/portable/running from source:
      NVDA installed
#### NVDA version:
      Version: alpha-22799,0a6806a3
#### Windows version:
      Windows 10 64-bit latest version (up to date)
#### Name and version of other software in use when reproducing the issue:
      Spring Tool Suite 4 
      Version: 4.5.1.RELEASE
      Build Id: 202001211336
      Eclipse.org	Eclipse RCP	4.14.0.v20191210-0610	
#### Other information about your system:
      Laptop 8GB of RAM, 64-bit processor 
#### Does the issue still occur after restarting your computer?
      Yes it does.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
      No I have not.
#### If add-ons are disabled, is your problem still occurring?
      When Eclipse Enhance is disabled the problem solved.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
      yes, it does.
      
      Thanks for This suitable add-on.
[nvda.log](https://github.com/albzan/eclipse-nvda/files/6510318/nvda.log)

**Comment by albzan** [comment]
Yes, that's because in the new release REASON_ have been dismissed. I've to update the coed in order to fix this, but I wait that this will be on a stable release.
